### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by myflashlab** [myflashlab/AR-ANE-Samples#11]
- [x] Run prototype on Android
- [x] Run prototype on iOS
- [x] Run Adhoc on iOS
- [x] Organizing the ANE for making it identical on both platforms
- [x] Building the core functionality 
- [x] Updating the PermissionCheck ANE to be better synced with the AR ANE
- [x] Device calibration listeners
- [x] JS to AIR and vice versa communication
- [x] Screenshot support from Augmented Reality scene
- [x] Adding support for camera hardware settings
- [x] Completing asdoc 
- [x] Completing Wiki and tutorials from 0 to 100 about AR usage in Adobe AIR

Built with ❤️ by MyFlashLabs Team

**Comment by benkhachouch** [comment]
Hello
I get à black screen when i select an item of the list  in the demo project.
And where put the target images to download?

Galaxy s6
Android 6.01

**Comment by myflashlab** [comment]
@benkhachouch the black screen is maybe happening because of the permissions thing when launching the video for the first time. Do you see the black screen for the next times you run the app? If so, can you send the AndroidStudio logcats? Have you tested this on other devices also?

**Comment by benkhachouch** [comment]
ok i'll verify

**Comment by benkhachouch** [comment]
yes
I see the black screen for the next times I run the
App.
Sorry i don't use android studio.

**Comment by benkhachouch** [comment]
And i use flash builder 4.6

**Comment by myflashlab** [comment]
@benkhachouch will you be able to send us your .apk?

**Comment by benkhachouch** [comment]
voila
https://drive.google.com/file/d/0B_0eb-FbNdkoZGF4R2JxUURtYmM/view?usp=sharing

2017-08-17 6:39 GMT+02:00 MyFlashLabs <notifications@github.com>:

**Comment by myflashlab** [comment]
@benkhachouch  your apk file is missing a LOT of assets! maybe we should add more details to the wiki... 🤔 in the mean while, try running the sample apk file we have put here: https://drive.google.com/drive/folders/0B7eHG2CEml2TN3B5emFxYlNkQXM?usp=sharing and tell me if it runs on your target device?

**Comment by benkhachouch** [comment]
Thanks you!
yes it run very good

**Comment by benkhachouch** [comment]
Yes i missed assets folder but i have error
"can't
found file:///android_asset/01_ImageTracking_1_ImageOnTarget/index.html"?
what is the android_asset?

2017-08-18 12:07 GMT+02:00 MyFlashLabs <notifications@github.com>:

**Comment by myflashlab** [comment]
```android_asset``` is ```File.applicationDirectory```

**Comment by benkhachouch** [comment]
thanks

**Comment by myflashlab** [comment]
updated the wiki a little bit more: https://github.com/myflashlab/AR-ANE-Samples/wiki/A.1.-Project-Setup#assets

**Comment by benkhachouch** [comment]
thanks you but

i change the with the new ane and new permissionscheck ane
i got
[AR_ANE-MyArchitectView]worldWasLoaded: url:
file:///android_asset/01_ImageTracking_1_ImageOnTarget/
AR World load succeeded for URL:
file:///android_asset/01_ImageTracking_1_ImageOnTarget/

but i have again the blackscreen

2017-08-18 13:08 GMT+02:00 MyFlashLabs <notifications@github.com>:

**Comment by myflashlab** [comment]
are you sure you have set the rest of the assets for the Android side as mentioned in the wiki?

**Comment by benkhachouch** [comment]
You are right
i missed
ade.js
<https://github.com/myflashlab/AR-ANE-Samples/blob/master/AIR/assets/ade.js>
V7.0.0-0.0.0
<https://github.com/myflashlab/AR-ANE-Samples/commit/e5c6cf0f80fda8e2527ec4a9c43ace009e362cb1>
9
days ago
architect.js
<https://github.com/myflashlab/AR-ANE-Samples/blob/master/AIR/assets/architect.js>
V7.0.0-0.0.0
<https://github.com/myflashlab/AR-ANE-Samples/commit/e5c6cf0f80fda8e2527ec4a9c43ace009e362cb1>
9
days ago
exit.png
<https://github.com/myflashlab/AR-ANE-Samples/blob/master/AIR/assets/exit.png>
V7.0.0-0.0.0
<https://github.com/myflashlab/AR-ANE-Samples/commit/e5c6cf0f80fda8e2527ec4a9c43ace009e362cb1>
9
days ago
sdk_logo-1.png
<https://github.com/myflashlab/AR-ANE-Samples/blob/master/AIR/assets/sdk_logo-1.png>
V7.0.0-0.0.0
<https://github.com/myflashlab/AR-ANE-Samples/commit/e5c6cf0f80fda8e2527ec4a9c43ace009e362cb1>
9
days ago
wikitude_icon.png
<https://github.com/myflashlab/AR-ANE-Samples/blob/master/AIR/assets/wikitude_icon.png>
V7.0.0-0.0.0
<https://github.com/myflashlab/AR-ANE-Samples/commit/e5c6cf0f80fda8e2527ec4a9c43ace009e362cb1>
9
days ago

   - © 2017 GitHub, Inc.


2017-08-18 13:44 GMT+02:00 MyFlashLabs <notifications@github.com>:

**Comment by benkhachouch** [comment]
hello
the ar  ane is more 100 Mega.
is it normal?

2017-08-18 13:58 GMT+02:00 mourad benkhachouch <
mourad.benkhachouch@gmail.com>:

**Comment by myflashlab** [comment]
> the ar ane is more 100 Mega.

of course it is normal. it includes builds for different frameworks and architectures including iOS and Android. They will not be directly included in your final app though.

**Comment by benkhachouch** [comment]
thanks

**Comment by benkhachouch** [comment]
your samples are ok.i got succes
 but when i test with my images and wtc that i genered it fail.

2017-08-18 17:17 GMT+02:00 mourad benkhachouch <
mourad.benkhachouch@gmail.com>:

> thanks
>

**Comment by benkhachouch** [comment]
your samples are ok.i got succes
 but when i test with my images and my wtc that i genered it fail.

Le 18 août 2017 17:21, a écrit :

thanks

Le 18 août 2017 17:05, "MyFlashLabs" <notifications@github.com> a écrit :

the ar ane is more 100 Mega.

of course it is normal. it includes builds for different frameworks and
architectures including iOS and Android. They will not be directly included
in your final app though.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/myflashlab/AR-ANE-Samples/issues/11#issuecomment-323378637>,
or mute the thread

**Comment by myflashlab** [comment]
The ANE job is to get the AR experience running in AIR. we can help you till that part :) If the samples are running, it means that we have completed our job. For more help, you need to ask Wikitude team directly. This page should help you: https://github.com/myflashlab/AR-ANE-Samples/wiki/A.9.-Where-to-go-from-here
